### ISSUE TITLE
Please share the weight file trained using LAG

### ISSUE THREAD

**Issue by ma-siddiqui** [leebebeto/Inter-Prototype#3]
Hi,

I am interested to test and evaluate your trained model on LAG data set. Please share its weight file.

Thanks,

**Comment by YeolJ00** [comment]
Hi there, 

Thanks for your interest in our work.

Our models (and most publicly available face recognition models) are trained with a large-scale dataset (CASIA WebFace and MS1M) and evaluated on a different test-set (e.g., LFW, AgeDB, and LAG).
Thus, if you intend to test our model on the LAG dataset, first download the model trained on the [Casia WebFace](https://drive.google.com/file/d/1g7wol0isBX_-X1r-TlTqaJk8pVWA5W4z/view?usp=sharing) or the 
[MS1Mv2](https://drive.google.com/file/d/1RFlHFqolCfDlZl43pHMoQOzobbn0MsaY/view?usp=sharing) and evaluate on the LAG test set. 

To clarify once again, the LAG dataset or any other test sets are only used as test sets do not have a separate training split.

Thanks again!
