### ISSUE TITLE
Clarification regarding section 5.2 in the paper

### ISSUE THREAD

**Issue by ElisonSherton** [leebebeto/Inter-Prototype#5]
Hi there!

I am really interested in your work and found it very relevant to a problem statement I am currently working on for my thesis.

> For the Inter-Prototype loss, we obtain (nchild, ntotal)=(229, 10,575) and (1,148, 85,742) in the CASIA-WebFace dataset [23] and MS1MV2, respectively

We come across the above statement toward the end of section 5.2. Do you mean that out of 85,742 identities in MS1MV2, 1148 contain at least one image which has a child image in it or do you mean these 1148 identities exclusively contain child images only; could you kindly elaborate on this?

Thanks,
Vinayak.

**Comment by leebebeto** [comment]
Hi thank you for the interests in our work

It means that we extract 229, 1148 identitites which include at least 10 child images for CASIA-WebFace and MS1MV2, respectively. Indeed, these identities also include adult images.

You can refer to https://github.com/leebebeto/Inter-Prototype/blob/master/data/data_pipe.py#L116 where args.child_filter is set to 10 as default.

Thank you! 
Jungsoo Lee

**Comment by leebebeto** [comment]
Hi there, I replied in the Github Issues

The reply is as follows:

Hi thank you for the interests in our work

It means that we exclude 229, 1148 identitites which include at least 10
child images for CASIA-WebFaceand MS1MV2, respectively. Indeed, these
identities also include adult images.

You can refer to
https://github.com/leebebeto/Inter-Prototype/blob/master/data/data_pipe.py#L116
where
args.child_filter is set to 10 as default.

Thank you!
Jungsoo Lee


2023년 8월 5일 (토) 오전 10:42, Vinayak Nayak ***@***.***>님이 작성:

**Comment by ElisonSherton** [comment]
OK, just to clarify, so basically you trained MS1MV2 with 85,742 - 1,148 = 85,594 identities respectively because there were 1148 identities which had less than 10 images whose age is between 0-12 years old.

Thanks!
Vinayak.

**Comment by leebebeto** [comment]
Oh so to talk precisely

We trained with ArcFace loss using all identities (85742 identities) and added Inter-prototype loss using 1148 identities, those including child images more than 10 images.

Thank you! 
Jungsoo Lee

**Comment by ElisonSherton** [comment]
Thank you so much for that info and a prompt response. Appreciate it.

Regards,
Vinayak.
